apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: exam-kube-clusterissuer
  labels:
    name: exam-kube-clusterissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: leandre.chavanne.y@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod 
    solvers:
    - http01:
        ingress:
          class: traefik
