apiVersion: v1
kind: Service
metadata:
  name: fastapi-clusterip
  namespace: standard
  labels:
    name: fastapi-clusterip
spec:
  selector:
    app: fastapi
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000

