apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Name}}-exam-pv
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.pv.storageClassName }}
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - {{ .Values.pv.accessMode }}
  hostPath:
    path: {{ .Values.pv.mountPath }}
