apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: standard
  labels:
    app: fastapi
    name: fastapi
spec:
  selector:
    matchLabels:
      app: fastapi
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: johndoe/kube-fastapi
          ports:
            - containerPort: 5000
