apiVersion: v1
kind: Service
metadata:
  name: pgadmin-clusterip
  namespace: standard
  labels:
    name: pgadmin-clusterip
spec:
  selector:
    app: pgadmin
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

