apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: standard
  labels:
    name: db
spec:
  selector:
    app: db-app
  type: ClusterIP
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432

