apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fastapi
  namespace:  {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-fastapi
    name: {{ .Release.Name }}-fastapi
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fastapi
  replicas: {{ .Values.fastapi.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fastapi
    spec:
      containers:
        - name: {{ .Release.Name }}-fastapi
          image: {{ .Values.fastapi.image}}
          ports:
            - containerPort: {{ .Values.fastapi.port}}