apiVersion: v1
kind: PersistentVolume
metadata:
  name: exam-pv
  namespace: standard
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
