apiVersion: v1
kind: Secret
metadata:
  name: db-rootpass
  namespace: standard
type: Opaque
data:
  #admin
  POSTGRES_USER: YWRtaW4=
  # password
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  # storedb
  POSTGRES_DB: c3RvcmVkYg==