apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-rootpass
  namespace: standard
type: Opaque
data:
  # admin@admin.com
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t
  # root
  PGADMIN_DEFAULT_PASSWORD: cm9vdA==