apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-pgadmin-rootpass
  namespace: {{ .Values.namespace }}
type: {{ .Values.secrets.pgadmin.type }}
data:
{{- range $k, $v := .Values.secrets.pgadmin.data }}
  {{ $k }}: {{ $v }}
{{- end }}
