apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fastapi-clusterip
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Release.Name }}-fastapi-clusterip
spec:
  selector:
    app: {{ .Release.Name }}-fastapi
  type: {{ .Values.services.fastapi.type }}
  ports:
    - name: {{ .Values.services.fastapi.name }}
      protocol: {{ .Values.services.fastapi.protocol }}
      port: {{ .Values.services.fastapi.port }}
      targetPort: {{ .Values.services.fastapi.targetPort }}

