apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgadmin-clusterip
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Release.Name }}-pgadmin-clusterip
spec:
  selector:
    app: {{ .Release.Name }}-pgadmin
  type: {{ .Values.services.pgadmin.type }}
  ports:
    - name: {{ .Values.services.pgadmin.name }}
      protocol: {{ .Values.services.pgadmin.protocol }}
      port: {{ .Values.services.pgadmin.port }}
      targetPort: {{ .Values.services.pgadmin.targetPort }}

