namespace: helm

fastapi:
  image: johndoe/kube-fastapi
  port: 5000
  replicas: 3

postgres:
  replicas: 2
  image: postgres:12.0-alpine
  port: 5432
  imagePullPolicy: IfNotPresent
  mountPath: /var/lib/postgresql/data

clusterIssuer:
  server: https://acme-v02.api.letsencrypt.org/directory
  email: john.doe@mail.com
  privateKeyRef: letsencrypt-prod
  ingressClass: traefik

pgadmin:
  image: dpage/pgadmin4
  imagePullPolicy: IfNotPresent
  port: 80

pv:
  storageClassName: local-path
  storage: 10Gi
  accessMode: ReadWriteOnce
  mountPath: "/mnt/data"

secrets:
  db:
    type: Opaque
    data:
      #admin
      POSTGRES_USER: YWRtaW4=
      # password
      POSTGRES_PASSWORD: cGFzc3dvcmQ=
      # storedb
      POSTGRES_DB: c3RvcmVkYg==
  pgadmin:
    type: Opaque
    data:
      # admin@admin.com
      PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t
      # root
      PGADMIN_DEFAULT_PASSWORD: cm9vdA==

services:
  db:
    type: ClusterIP
    name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  pgadmin:
    type: ClusterIP
    name: pgadmin
    protocol: TCP
    port: 80
    targetPort: 80
  fastapi:
    type: ClusterIP
    name: fastapi
    protocol: TCP
    port: 80
    targetPort: 80

ingress:
  className: "traefik"
  secretName: "secrettls"
  annotations: {
    cert-manager.io/cluster-issuer: exam-kube-clusterissuer
  }
  hosts:
    - host: kube-exam-helm.com
      serviceName: fastapi-clusterip
    - host: kube-pgadmin-helm.com
      serviceName: pgadmin-clusterip

autoscaling:
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

